### PR TITLE
[DPE-5289]: CI uses new juju versions

### PR DESCRIPTION
**Pull request by Gu1nness**
## Issue

* We need to keep CI up to date 

## Solution

* Use juju 3.5.3 in regular runs
* Runs also 3.6/beta on nightly runs

### CODE REVIEW

**Review by carlcsaposs-canonical — DISMISSED** [review]
you may need to specify base when deploying with libjuju so that it doesn't default to focal cc @shayancanonical

**Review by Mehdi-Bendriss — APPROVED** [review]

**Review by MiaAltieri — COMMENTED** [review]
There are quite a few failing tests.

Are these new to this PR or are these tests failing on CI regularly?

**Comment by Gu1nness** [comment]
> There are quite a few failing tests.
> 
> Are these new to this PR or are these tests failing on CI regularly?

I need to check!

EDIT: the sharding relation is expected to fail. The other ones I will run it again but they just passed on a new run.

**Comment by Gu1nness** [comment]
Yeah stable.

**Comment by MiaAltieri** [comment]
Note for readers test failing will be addressed #473

**Review by MiaAltieri — APPROVED** [review]

**Pull request merged**
