### PR TITLE
fix: include extra files with the 'dump' plugin

### PR DESCRIPTION
**Pull request by lengau**
## Issue

In Charmcraft 3, the behaviour of the `prime` keyword has changed, and the warning and documentation are not clear about the change. See: https://github.com/canonical/charmcraft/issues/1782

## Solution

Use the `dump` plugin to include extra files, priming only the files needed.

### CODE REVIEW

**Comment by MiaAltieri** [comment]
Thank you so much for your PR to Charmed MongoDB @lengau . 

It appears that since we upgraded to new runners on this repo, the int tests in your repo are failing. Let us look into changing permissions. 

If this is blocking for your work, please let me know and I can make this PR separately

**Comment by Mehdi-Bendriss** [comment]
/canonical/self-hosted-runners/run-workflows bd75297e8e9560b390a1942dfca0bd0066dca823

**Comment by Mehdi-Bendriss** [comment]
/canonical/self-hosted-runners/run-workflows bd75297e8e9560b390a1942dfca0bd0066dca823

**Review by Mehdi-Bendriss — APPROVED** [review]

**Comment by Mehdi-Bendriss** [comment]
Merging as the tests failure is due to the Github secrets not being available for PRs made through forks.

**Pull request merged**
