### PR TITLE
fix (tests): ensure that the leader is managing secrets

### PR DESCRIPTION
**Pull request by tonyandrewmeyer**
## Issue

As of ops 2.10+ `Harness` applies the same access controls to secrets as Juju does in production. This causes tests to fail that were ignoring these access restrictions (deliberately - they have docstrings that call it out).

## Solution

Set the unit to be leader in each of the applicable tests. It might be that you'd rather have tests for both cases, leader and (failing appropriately) non-leader - I can adjust to do that if you prefer.

### CODE REVIEW

**Comment by Mehdi-Bendriss** [comment]
Hello @tonyandrewmeyer, thanks for the PR! 

Apologies for the delay, we're finally getting around tackling these issues as we're [upgrading all dependencies](https://github.com/canonical/mongodb-operator/pull/395).

Could you please add the test case you mentioned? (failure in case non-leader attempts to manage secrets)?

**Comment by tonyandrewmeyer** [comment]
> Could you please add the test case you mentioned? (failure in case non-leader attempts to manage secrets)?

Sure - done!

**Review by Mehdi-Bendriss — APPROVED** [review]
Thank you!

**Review by MiaAltieri — APPROVED** [review]
Looks good to me. Thank you very much @tonyandrewmeyer

**Pull request merged**
